<?php
        //Pour la connexion à la base de donnée
        $this->config["host"] = 'localhost';
        $this->config["db_name"] = 'akoy_prestation';
        $this->config["username"] = 'root';
        $this->config["password_"] = '';
$this->config["tables"] = ['academie','association','categorie_type_publication','categories_publication','client','competence','cv','cv_academie','cv_association','cv_competence','cv_experience','cv_langue','cv_projet','ecole','entreprise','experience','experience_tache','files','filieres','langues','module','module_role','pays','projet','publications','publicites','roles','tache','type_publication','types_user','users','villes','vues',];

$this->config['tables']['academie'] = ['id','ecole','filiere','date_debut','date_fin','ville','diplome',];

$this->config['tables']['academie']['id'] = ['id'];

$this->config['tables']['association'] = ['id','titre',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];

$this->config['tables']['categorie_type_publication'] = ['id','categories_publication','type_publication',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];

$this->config['tables']['categories_publication'] = ['id','titre','icon','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];

$this->config['tables']['client'] = ['id','nom','prenom','phone','email','statut','ville','presentation','adresse','created_at','update_at','password','file','date_naissance','lieu_naissance',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];

$this->config['tables']['competence'] = ['id','titre',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];

$this->config['tables']['cv'] = ['id','client','created_at','update_at','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];

$this->config['tables']['cv_academie'] = ['id','cv','academie',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];

$this->config['tables']['cv_association'] = ['id','cv','association',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];

$this->config['tables']['cv_competence'] = ['id','cv','competence',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];

$this->config['tables']['cv_experience'] = ['id','cv','experience',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];

$this->config['tables']['cv_langue'] = ['id','cv','langue',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];

$this->config['tables']['cv_projet'] = ['id','cv','projet',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];

$this->config['tables']['ecole'] = ['id','label','description','ville','user_create','created_at','updated_at','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];

$this->config['tables']['entreprise'] = ['id','titre','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];

$this->config['tables']['experience'] = ['id','entreprise','poste','date_debut','date_fin','ville','tache',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];

$this->config['tables']['experience_tache'] = ['id','experience','tache',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];

$this->config['tables']['files'] = ['id','file_name','file_url','file_type','file_size','created_at','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];

$this->config['tables']['filieres'] = ['id','titre','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];

$this->config['tables']['langues'] = ['id','code','titre','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];

$this->config['tables']['module'] = ['id','name','icon','description','action_url','sub_module','is_menu','created_at','updated_at','statut','user_create',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];

$this->config['tables']['module_role'] = ['id','role_id','module','create_at',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];

$this->config['tables']['pays'] = ['id','name',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];

$this->config['tables']['projet'] = ['id','titre','liens',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];

$this->config['tables']['publications'] = ['id','type_publication','category_publication','num_offre','titre','description','lieu','date_annee_bourse','date_debut','date_fin','ecole','date_elaboration','file','user_create','create_at','updated_at','statut','ville','entreprise','experience','sexe','nombre_candidat','diplome','salaire',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];

$this->config['tables']['publicites'] = ['id','titre','description','file','entreprise','delai','user_create','created_at','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];$this->config['tables']['publicites']['id'] = ['id'];

$this->config['tables']['roles'] = ['id','name','description','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];$this->config['tables']['publicites']['id'] = ['id'];$this->config['tables']['roles']['id'] = ['id'];

$this->config['tables']['tache'] = ['id','titre',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];$this->config['tables']['publicites']['id'] = ['id'];$this->config['tables']['roles']['id'] = ['id'];$this->config['tables']['tache']['id'] = ['id'];

$this->config['tables']['type_publication'] = ['id','titre','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];$this->config['tables']['publicites']['id'] = ['id'];$this->config['tables']['roles']['id'] = ['id'];$this->config['tables']['tache']['id'] = ['id'];$this->config['tables']['type_publication']['id'] = ['id'];

$this->config['tables']['types_user'] = ['id','label','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];$this->config['tables']['publicites']['id'] = ['id'];$this->config['tables']['roles']['id'] = ['id'];$this->config['tables']['tache']['id'] = ['id'];$this->config['tables']['type_publication']['id'] = ['id'];$this->config['tables']['types_user']['id'] = ['id'];

$this->config['tables']['users'] = ['id','first_name','last_name','phone_number','type_user','created_at','updated_at','photo','role','password_','statut','statut_delete',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];$this->config['tables']['publicites']['id'] = ['id'];$this->config['tables']['roles']['id'] = ['id'];$this->config['tables']['tache']['id'] = ['id'];$this->config['tables']['type_publication']['id'] = ['id'];$this->config['tables']['types_user']['id'] = ['id'];$this->config['tables']['users']['id'] = ['id'];

$this->config['tables']['villes'] = ['id','titre','pays','statut',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];$this->config['tables']['publicites']['id'] = ['id'];$this->config['tables']['roles']['id'] = ['id'];$this->config['tables']['tache']['id'] = ['id'];$this->config['tables']['type_publication']['id'] = ['id'];$this->config['tables']['types_user']['id'] = ['id'];$this->config['tables']['users']['id'] = ['id'];$this->config['tables']['villes']['id'] = ['id'];

$this->config['tables']['vues'] = ['id','id_publication','created_at','nb',];

$this->config['tables']['academie']['id'] = ['id'];$this->config['tables']['association']['id'] = ['id'];$this->config['tables']['categorie_type_publication']['id'] = ['id'];$this->config['tables']['categories_publication']['id'] = ['id'];$this->config['tables']['client']['id'] = ['id'];$this->config['tables']['competence']['id'] = ['id'];$this->config['tables']['cv']['id'] = ['id'];$this->config['tables']['cv_academie']['id'] = ['id'];$this->config['tables']['cv_association']['id'] = ['id'];$this->config['tables']['cv_competence']['id'] = ['id'];$this->config['tables']['cv_experience']['id'] = ['id'];$this->config['tables']['cv_langue']['id'] = ['id'];$this->config['tables']['cv_projet']['id'] = ['id'];$this->config['tables']['ecole']['id'] = ['id'];$this->config['tables']['entreprise']['id'] = ['id'];$this->config['tables']['experience']['id'] = ['id'];$this->config['tables']['experience_tache']['id'] = ['id'];$this->config['tables']['files']['id'] = ['id'];$this->config['tables']['filieres']['id'] = ['id'];$this->config['tables']['langues']['id'] = ['id'];$this->config['tables']['module']['id'] = ['id'];$this->config['tables']['module_role']['id'] = ['id'];$this->config['tables']['pays']['id'] = ['id'];$this->config['tables']['projet']['id'] = ['id'];$this->config['tables']['publications']['id'] = ['id'];$this->config['tables']['publicites']['id'] = ['id'];$this->config['tables']['roles']['id'] = ['id'];$this->config['tables']['tache']['id'] = ['id'];$this->config['tables']['type_publication']['id'] = ['id'];$this->config['tables']['types_user']['id'] = ['id'];$this->config['tables']['users']['id'] = ['id'];$this->config['tables']['villes']['id'] = ['id'];$this->config['tables']['vues']['id'] = ['id'];
